# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Construition et envoi de l'image docker sur le hub
      uses: docker/build-push-action@v1.1.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: sundayoyeniyi/spring-starter
        tags: 1.0.2
        tag_with_ref: true
        tag_with_sha: true
    
    - name: Execution de la commande ssh sur le serveur à deployer
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ${{ secrets.AWS_USER }}
        key: ${{ secrets.AWS_KEY }}
        port: ${{ secrets.AWS_PORT }}
        script: |
          sudo docker stop springb-greeting-app
          sudo docker rm springb-greeting-app
          sudo docker pull sundayoyeniyi/spring-starter
          sudo docker run -d --name springb-greeting-app -p 8081:8080 sundayoyeniyi/spring-starter
          sudo docker ps
